#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=72,1,2,6,7,8,14,41,43,65,67&i=1,2,3,4,15,16,17,39,41&v=4,5,-1,2,27,26,25,32,15 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, Adafruit ST7735 and ST7789 Library, IRremoteESP8266 */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define DSP_MODEL			DSP_ST7789
#define BRIGHTNESS_PIN			2
#define SD_HSPI			true
#define SDC_CS			32
#define IR_PIN			15
//#define RSSI_DIGIT true

//#define HIDE_DATE 
//#define CLOCKFONT_MONO false
#define CLOCK_TTS_ENABLED  1                            // 1 = włączone, 0 = wyłączone
#define CLOCK_TTS_LANGUAGE "ro"                         // Domyślny język TTS (np. pl,en,de,ru,fr,hu)
#define CLOCK_TTS_INTERVAL_MINUTES 60                   // Domyślny interwał ogłaszania (w minutach, np. 1, 5, 15, 30, 60)
#define BOOMBOX_STYLE
#define VU_PEAK
#define BATTERY_OFF               /* Отключить показатель уровня заряда и напряжения аккумулятора */
#define HIDE_VOLT

#endif
