//========================================================================
int un = 110-1;     // Change depending on the number of URLs
char *url[110] = {  // url*Station name

  "https://radio-stream.nhk.jp/hls/live/2023229/nhkradiruakr1/master.m3u8*NHK Tokyo 1",
  "https://radio-stream.nhk.jp/hls/live/2023501/nhkradiruakr2/master.m3u8*NHK Tokyo 2",
  "https://radio-stream.nhk.jp/hls/live/2023507/nhkradiruakfm/master.m3u8*NHK Tokyo FM",
  "https://radio-stream.nhk.jp/hls/live/2023545/nhkradiruikr1/master.m3u8*NHK Saporo 1",
  "https://radio-stream.nhk.jp/hls/live/2023546/nhkradiruikfm/master.m3u8*NHK Saporo FM",
  "https://radio-stream.nhk.jp/hls/live/2023543/nhkradiruhkr1/master.m3u8*NHK Sendai 1",
  "https://radio-stream.nhk.jp/hls/live/2023544/nhkradiruhkfm/master.m3u8*NHK Sendai FM",
  "https://radio-stream.nhk.jp/hls/live/2023510/nhkradiruckr1/master.m3u8*NHK Nagoya 1",
  "https://radio-stream.nhk.jp/hls/live/2023511/nhkradiruckfm/master.m3u8*NHK Nagoya FM",
  "https://radio-stream.nhk.jp/hls/live/2023508/nhkradirubkr1/master.m3u8*NHK Osaka 1",
  "https://radio-stream.nhk.jp/hls/live/2023509/nhkradirubkfm/master.m3u8*NHK Osaka FM",
  "https://radio-stream.nhk.jp/hls/live/2023512/nhkradirufkr1/master.m3u8*NHK Hiroshima 1",
  "https://radio-stream.nhk.jp/hls/live/2023513/nhkradirufkfm/master.m3u8*NHK Hiroshima FM",
  "https://radio-stream.nhk.jp/hls/live/2023547/nhkradiruzkr1/master.m3u8*NHK Matuyama 1",
  "https://radio-stream.nhk.jp/hls/live/2023548/nhkradiruzkfm/master.m3u8*NHK Matuyama FM",
  "https://radio-stream.nhk.jp/hls/live/2023541/nhkradirulkr1/master.m3u8*NHK Fukuoka 1",
  "https://radio-stream.nhk.jp/hls/live/2023542/nhkradirulkfm/master.m3u8*NHK Fukuoka FM",
  "http://radio.kahoku.net:8000/;?type=http&nocache=652*FMkahoku",

  "https://kuer.streamguys1.com/kuer2high_icy*BBC",
  "https://stream.xmission.com/kuaa*KUAA",
  //"https://stream.xmission.com/krcl-high*KRCL",
  "http://streams.kpfa.org:8000/kpfa*KPFA",
  //"http://live.str3am.com:2470/live32.m3u*KMUD",
  //"http://peace.str3am.com:6650/*KHSU",
  "https://stream.wbez.org/wbez64-web.aac*WBEZ",
  "https://kuer.streamguys1.com/high_icy*KUER",
  "http://player.netstreambolivia.com/player/7278/vlc.m3u*La Joya Bolivia",
  "https://player.srvstm.com/player/8612/vlc.m3u*RADIO TIAHUANAKU BOLIVIA",
  "https://s2.mexside.net/8030/stream*Tropicalisima Mexico DF",
  "http://espora.org:8000/jenpojradio*Radio Jenpoj Oaxaca",
  "http://radios.liberaturadio.org:8000/fmcholollan*Cholollan San Bernardino Tlaxcalancingo, PU, Mexico",
  "https://node-23.zeno.fm/dgau5893mp8uv*Maranki Peru",
  "https://streams.radio.co/sed33484dc/listen*Canada's First Nations University Radio",
  "http://radiobarriletes.sytes.net:8000/barriletes*Radio Comunitaria Cuyum Mendoza Argentina",
  "http://freeuk22.listen2myradio.com:6457/*Radio Comunitaria Aiquile Bolivia",
  "http://comecuco.org:8000/Cuyum*Radio Comunitaria Cuyum Mendoza Argentina",
  "http://165.22.114.167:8099/;?type=http&nocache=1*Rádio Comunitária de Santa Maria Cape Verde",
  "http://war.str3am.com:7040/live-mp3*Dryland Community Radio Cortez, CO",
  "http://ednixon.com:8170/stream*KQBH Community Radio",
  "https://s2.radio.co/sb23429e9f/listen*Radio Universidad de Navarra España",
  "https://cervera.eldialdigital.com:25191/stream*ECO Leganés España",

  "http://ice1.somafm.com/illstreet-128-mp3*SomaFM/Illinois Street Lounge",
  "http://ice1.somafm.com/secretagent-128-mp3*SomaFM/Secret Agent",
  "http://ice1.somafm.com/seventies-128-mp3*SomaFM/Left Coast 70s",
  "http://ice1.somafm.com/bootliquor-128-mp3*SomaFM/Boot Liquor",

  "http://wbgo.streamguys.net/thejazzstream*jazzstream",
  "http://ais-sa2.cdnstream1.com/b22139_128mp3*101 SMOOTH JAZZ",
  "http://listen.181fm.com/181-beatles_128k.mp3*181-beatles_128k",
  "http://ice1.somafm.com/illstreet-128-mp3*SomaFM/Illinois Street Lounge",
  "http://relax.stream.publicradio.org/relax.mp3*Your Classical - Relax",
  "http://ice1.somafm.com/secretagent-128-mp3*SomaFM/Secret Agent",
  "http://ice1.somafm.com/seventies-128-mp3*SomaFM/Left Coast 70s",
  "http://ice1.somafm.com/bootliquor-128-mp3*SomaFM/Boot Liquor",
  "https://somafm.com/indiepop.pls*SomaFM/Indie Pop Rocks!",
  "http://us5.internet-radio.com:8201/stream?type=http&nocache=148896*Keith Jarrett-Over The Rainbow",
  "http://us2.internet-radio.com:8046/stream?type=http&nocache=87360/*Matt Johnson Radio",
  "http://uk5.internet-radio.com:8174/stream?type=http&nocache=2872*Joy Radio",
  "http://us2.internet-radio.com:8443/listen.pls&t=.m3u*MEGATON CAFE RADIO",
  "http://us2.internet-radio.com:8443/stream?type=http&nocache=84274*RADIO ESTILO LEBLON",
  "http://s1.viastreaming.net:8000/;?type=http&nocache=1262945*Smooth Choice",
  "http://wbgo.streamguys.net/wbgo96*WBGO FM 96",
  "http://play.global.audio/bgradio128*RADIO BGRADIO",
  "http://live.antenne.at/as*Antenne Steiermark",
  "http://naxos.cdnstream.com:80/1255_128*Lite Favorites",
  "http://funkhaus-ingolstadt.stream24.net/radio-in.mp3*funkhaus-ingolstadt.stream24",
  "http://stream.rockantenne.de/rockantenne/stream/mp3*rockantenne",
  "http://wdr-wdr2-ruhrgebiet.icecast.wdr.de/wdr/wdr2/ruhrgebiet/mp3/128/stream.mp3*ruhrgebiet",
  "http://www.ndr.de/resources/metadaten/audio/m3u/ndr2.m3u*ndr2",
  "http://vis.media-ice.musicradio.com/CapitalMP3*CapitalMP3",
  "http://0n-80s.radionetz.de:8000/0n-70s.mp3*0n-70s",
  "http://0n-80s.radionetz.de:8000/*radionetz",
  "http://streams.br.de/bayern3_2.m3u*bayern3_2",
  "http://play.antenne.de/antenne.m3u*antenne",
  "http://streams.radiobob.de/bob-national/mp3-192/streams.radiobob.de/*streams.radiobob",
  "http://108.61.154.147:6978/stream?type=http&nocache=4853/*The Nemesis Radio",
  "http://51.81.46.118:3340/;?type=http&nocache=567205/*J-Rock PowerPlay",
  "http://us3.internet-radio.com:8232/stream?type=http&nocache=128897*Radio Cherwell - Hospital Radio in Oxford",
  "http://uk5.internet-radio.com:8237/stream?type=http&nocache=739*Stoke Mandeville Hospital Radio",
  "http://uk7.internet-radio.com:8040/stream?type=http&nocache=16709*Ava Max - Sweet But Psycho",
  "http://allstream.rainwave.cc:8000/all.mp3*Rainwave All",
  "http://sc6.radiocaroline.net:8040/;?type=http&nocache=42646listen.pls*Radio Caroline",
  "http://sc6.radiocaroline.net:10558/;?type=http&nocache=9769*Radio Caroline Flashback",
  "http://listen.181fm.com/181-oldschool_128k.mp3*181 F M Old School",
  "http://listen.181fm.com/181-90sdance_128k.mp3*181 F M Nineties Dance",
  "http://listen.181fm.com/181-chilled_128k.mp3*181 F M Chilled",
  "http://listen.181fm.com/181-classical_128k.mp3*181 F M Classical",
  "http://ice2.somafm.com/christmas-128-mp3*SomaFM Xmas",
  "http://streamer.radio.co/s06b196587/listen*KPop Way Radio",
  "http://media-ice.musicradio.com:80/ClassicFMMP3*Classic FM",
  "http://188.138.9.183/lounge-austria-mobile.mp3*Unspecified name",
  "http://listen2.myradio24.com:9000/8144*Radio Magic",
  "http://91.211.56.218:8080/piramida/nazarovo*Radio Piramida FM",
  "http://live.coolradio.rs/cool128*COOL radio | Serbia",
  "http://ais-edge16-jbmedia-nyc04.cdnstream.com/hot108*HOT 108 JAMZ",
  "http://streams.iloveradio.de/iloveradio1.mp3*I Love Radio",
  "http://icy.unitedradio.it/VirginRogerWaters.mp3*PinkFloyd",
  "http://live.m2stream.fr/m280-128.mp3*M2 80's",
  "http://live.m2stream.fr/m2hit-128.mp3*M2 Hit's",
  "http://live.m2stream.fr/m2club-128.mp3*M2 Club",
  "http://live.m2stream.fr/m2love-128.mp3*M2 Love",
  //"http://live.m2stream.fr/m2rock-128.mp3*M2 Rock",
  "http://live.m2stream.fr/m2sunshine-128.mp3*M2 Sunshine",
  "http://airspectrum.cdnstream1.com:8000/1261_192*Magic Oldies Florida",
  "http://rockthecradle.stream.publicradio.org/radioheartland.mp3*Radio Heartland - MPR",
  //"http://opera-stream.wqxr.org/wnycam-app*WNYC-AM - New York Public Radio",
  "http://sc8.radiocaroline.net/;*Radio Caroline",
  "http://uk1.internet-radio.com:8355/stream?type=http&nocache=14021*The Zone - Dublin",
  //"http://uk5.internet-radio.com:8011/stream?type=http&nocache=158*Top 80 radio",
  "http://us3.internet-radio.com:8496/stream?type=http&nocache=241*RaveRocksRadio",
  "http://uk7.internet-radio.com:8168/stream?type=http&nocache=1226*242 RADIO stream",
  "http://us2.internet-radio.com:8443/stream?type=http&nocache=84424stream?type=http&nocache=84414*MEGATON CAFE RADIO",
  "http://us2.internet-radio.com:8046/stream?type=http&nocache=87328*us2.internet-radio",
  "http://media-ice.musicradio.com:80/ClassicFMMP3*media-ice.musicradio",
  "http://listen.181fm.com/181-uktop40_128k.mp3*181 F M Top 40"

};
//========================================================================
// http://icecast.omroep.nl
// http://github.com/pilnikov/KaRadio32_fork/blob/master/playlist/WebStations.txt
// http://fmstream.org
// http://www.internet-radio.com
// https://gist.github.com/riocampos/93739197ab7c765d16004cd4164dca73   NHK
// https://www.internet-radio.com/stations/jazz/
//========================================================================
