; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps = 
	sebmillet/RF433any@^0.7.7
	mikem/VirtualWire@^1.27
	zwer2k/WeatherStationDataRx@^0.5.0
	mbed-thechrisyd/RCSwitch@0.0.0+sha.6f4be1a7962c
